### ISSUE TITLE
Eaves with truss, cantilever roof structure

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-Beopt#49]
Truss, cantilever roof structure increases the height of the roof decks. Currently the vertical walls just below the roof decks (with exception of the triangular walls for gable roofs) do not extend all the way up to reach the roof decks. Should they?

![image](https://cloud.githubusercontent.com/assets/8516790/15118033/a3f9c2a8-15c7-11e6-96a0-ee070dff0301.png)

@shorowit

**Comment by shorowit** [comment]
We can't simply extend the wall up to the roof deck (or alternatively extend the attic floor out to the roof deck) because the space associated with these surface extensions would be wrong. For example, if you extended the wall up to the roof deck, the wall extension inside the attic would still be calculating heat transfer between living space and outside. To fix this, we'd actually have to create new surfaces. And then we'd have to make sure constructions are assigned appropriately...

That all said, I'm OK with how things are as. It's a pretty small detail.

**Comment by shorowit** [comment]
We can't simply extend the wall up to the roof deck (or alternatively extend the attic floor out to the roof deck) because the space associated with these surface extensions would be wrong. For example, if you extended the wall up to the roof deck, the wall extension inside the attic would still be calculating heat transfer between living space and outside. To fix this, we'd actually have to create new surfaces. And then we'd have to make sure constructions are assigned appropriately...

That all said, I'm OK with how things are as. It's a pretty small detail.

**Comment by shorowit** [comment]
We can't simply extend the wall up to the roof deck (or alternatively extend the attic floor out to the roof deck) because the space associated with these surface extensions would be wrong. For example, if you extended the wall up to the roof deck, the wall extension inside the attic would still be calculating heat transfer between living space and outside. To fix this, we'd actually have to create new surfaces. And then we'd have to make sure constructions are assigned appropriately...

That all said, I'm OK with how things are as. It's a pretty small detail.
