### ISSUE TITLE
HPWH measure

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#58]
High priority:
- [x] Debugging of EMS
- [x] Fix code for replacing an existing HPWH (currently removing some unnamed schedules that are created by other measures, check if we can just leave those in without them affecting energy results)
- [x] Update warning and error messages for the HPWH
- [x] Comment out ducting arguments
- [x] Update waterheater.rb to work with HPWHs
- [x] Get an updated OS 2.0 build with the change to remove unnecessary source side nodes
- [x] Add unit tests for the HPWH measure

**Comment by shorowit** [comment]
Would be good to see where we can simplify/hardcode inputs and/or whether we can calculate values based on EF?

**Comment by jmaguire1** [comment]
I just got Kyle to fix a bug with the forward translation that was preventing the HPWH model from running (https://github.com/NREL/OpenStudio/commit/4eb8b8590b45dcfb64c50b6d52243d93c4e33226). This means I'll have to use his dev branch, which is OS 2.0, to get this measure running. He's also on the hook to update the model to allow 12 nodes next year when he has time.

We're also about to get all of the HPWH lab testing data that Ecotope has, as well as access to the source code of their model. Our models are of units from ~5 years ago. I'd say there's a real need to update our models, and getting all this data for free makes now seem like a good time. Once I get all the data we should talk about potentially making updating our models part of this project, or if we could propose a small task to BPA/DOE/someone else.

**Comment by shorowit** [comment]
@jmaguire1: Can we proceed with using 10 nodes for the time being?

**Comment by jmaguire1** [comment]
Yes, we can proceed with 10 nodes for now.

**Comment by jmaguire1** [comment]
Noel's been having some trouble actually building OS 2.0 for me, he's getting some memory related issues and might not be able to get help from the OS team until after the holidays. In the meantime, I can test the measure if I manually delete the extra source side nodes from the .idf or write an E+ measure to remove them. I think I'll probably just delete them manually for testing purposes and try to do a lot of debugging on the .idf results without trying to rerun the measure too many times since this is just a stopgap for the next week.

On the Ecotope data front, I verified that their generic model uses the defaults from the latest GE unit. GE is stopping production of their HPWH at the end of the year, and they had a unique control logic, so I'm not sure we'll want to exactly use what they have. Them stopping production was a big surprise to a lot of people and they'd dominated market share up until now, which is likely why it was set up this way. Here's a list of the models they have available in SEEM:

    // these models are based on real tanks and measured lab data 
    // AO Smith models
    MODELS_AOSmithPHPT60 = 102,         /**< this is the Ecotope model for the 60 gallon Voltex HPWH  */
    MODELS_AOSmithPHPT80 = 103,         /**<  Voltex 80 gallon tank  */
    MODELS_AOSmithHPTU50 = 104,    /**< 50 gallon AOSmith HPTU */ 
    MODELS_AOSmithHPTU66 = 105,    /**< 66 gallon AOSmith HPTU */ 
    MODELS_AOSmithHPTU80 = 106,    /**< 80 gallon AOSmith HPTU */ 

    // GE Models
    MODELS_GE2012 = 110,      /**<  The 2012 era GeoSpring  */
    MODELS_GE2014STDMode = 111,    /**< 2014 GE model run in standard mode */ 
    MODELS_GE2014STDMode_80 = 113,    /**< 2014 GE model run in standard mode, 80 gallon unit */ 
    MODELS_GE2014 = 112,           /**< 2014 GE model run in the efficiency mode */
    MODELS_GE2014_80 = 114,           /**< 2014 GE model run in the efficiency mode, 80 gallon unit */

    // Sanden CO2 transcritical heat pump water heaters
    MODELS_Sanden40 = 120,        /**<  Sanden 40 gallon CO2 external heat pump  */
    MODELS_Sanden80 = 121,        /**<  Sanden 80 gallon CO2 external heat pump  */

    // The new-ish Rheem
    MODELS_RheemHB50 = 140,        /**< Rheem 2014 (?) Model */

    // The new-ish Stiebel
    MODELS_Stiebel220E = 150,      /**< Stiebel Eltron (2014 model?) */

    // Generic water heaters, corresponding to the tiers 1, 2, and 3
    MODELS_Generic1 = 160,         /**< Generic Tier 1 */
    MODELS_Generic2 = 161,         /**< Generic Tier 2 */
    MODELS_Generic3 = 162,          /**< Generic Tier 3 */


    MODELS_UEF2generic = 170,   /**< UEF 2.0, modified GE2014STDMode case */
    MODELS_genericCustomUEF = 171,   /**< used for creating "generic" model with custom uef*/

I think we can still look at their generic model, but we might want to default to the AO Smith control logic and possibly performance curves as well. Also interesting is the addition of some CO2 HPWHs (Sanden units), something we don't have that the PNW has been very excited about. Looks like lots of things we can potentially do with this data once we get the base model debugged and running in an OS 2.0 build.

**Comment by jmaguire1** [comment]
TODO list for this measure:

- [ ] Get an updated OS 2.0 build with the change to remove unnecessary source side nodes
- [ ] Update warning and error messages for the HPWH
- [ ] Add interaction with the airflow measure for ducting configurations (likely will require airflow measure to be run before the HPWH measure when ducting is used)
- [ ] Debugging of EMS
- [ ] Add code for replacing an existing HPWH
