### ISSUE TITLE
Garage enhancement

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-Beopt#65]
In the geometry measure, it'd be nice to allow a garage protrusion input (0-100%). The current assumption (completely inset) causes some problems for some of our ResStock models depending on house size and # stories.

Some thoughts/questions:
- How to handle interaction with aspect ratio?
- Add checkbox for bonus room?
- Roof interaction (for 1-story and 2+ story buildings)

**Comment by joseph-robertson** [comment]
Need to update the eaves measure to handle the following scenarios:
- one-story flat roof with garage (challenge: adding eaves to the flat roof when not a four vertex rectangle)
![image](https://cloud.githubusercontent.com/assets/8516790/15690929/3789d44a-2743-11e6-8457-41a34d44d3f5.png)

- one-story gable roof with garage, aspect ratio < 1 (challenge: extending the attic wall that has four vertices instead of the usual three)
![image](https://cloud.githubusercontent.com/assets/8516790/15691018/b2314a34-2743-11e6-96da-e92644d606ed.png)

**Comment by joseph-robertson** [comment]
Roof type of the garage should be the same as roof type of the building.

**Comment by joseph-robertson** [comment]
Updates:
- Remove bonus room argument (assume bonus room all the way up if garage protrudes -> yields single L-shaped roof)
- Always have garage ridge running front/back
- Error if garage protrusion > 0 and:
 - hip roof
 - house ridge runs front to back (Aspect Ratio > 1 or Aspect Ratio >= 1?)
 - garage ridge height > house ridge height

**Comment by joseph-robertson** [comment]
Eaves measure fails to raise the deck between the garage and unfinished attics:

![image](https://cloud.githubusercontent.com/assets/8516790/16156688/a7ce7198-3472-11e6-942c-0cae1924d869.png)

**Comment by joseph-robertson** [comment]
@joseph-robertson to revisit this. Also to confirm that there is no surface between garage and garage attic.

**Comment by joseph-robertson** [comment]
Lookin' good now (except for the shading object that runs through the garage attic, but hopefully this doesn't matter).

![image](https://cloud.githubusercontent.com/assets/8516790/16700749/e43f9812-4518-11e6-9872-4a2abd6b5f9c.png)

**Comment by shorowit** [comment]
Will open a separate low-priority ticket for the extra eaves area/surface.
