### ISSUE TITLE
Solar DHW

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#69]
Will need for RESNET. Can look at existing BEopt model.

**Comment by joseph-robertson** [comment]
Issues:
- [ ] eplusout.err: Autosizing of Source side water heater design flow rate requires Sizing:Plant object to have an exit temperature >= 58C
- [ ] How to attach availability manager to the plant loop?

@jmaguire1

**Comment by jmaguire1** [comment]
Some notes on the current state of things:

- The source side flow rate is being autosized in a few places in both BEopt and OS. In OS, this causes an issue since the autosizing is looking for a specific outlet temperature to be > 60 C and it's about 58 C. This doesn't happen in BEopt, but there's also a few missing objects in OS that may be the cause of this, not sure which one it is just yet.
-  The source side flow rate doesn't need to be autosized in either case. The max flow rate calculated for the collector, and since a constant speed pump is used, that same max flow rate is used by the collector, pump, and stratified WH. We can avoid the autosizing issue entirely by just hard sizing to this value. I checked that BEopt ends up using this hard sized value everywhere, so it won't impact results. Doing this will fix the E+ error we're currently seeing related to autosizing.
- The collector flow rate isn't being calculated correctly in the current measure. I think this is just a unit conversion issue, but it'll need to be fixed.
- We need to be able to specify a glycol/water mix for the flat plate collector rather than using water. I think we also need this for #66, but it looks like there's an object that needs to be wrapped before we can do this.
- The missing controllers don't affect autosizing, but might lead to the SWH pump running continuously. We'll want to check how everything is actually being controlled as the next step after fixing the autosizing issue so we can see if we need new objects wrapped to control the SWH loop correctly or if we can work around the issues we're seeing now.

**Comment by shorowit** [comment]
Final testing pending.
