### ISSUE TITLE
Update MonthWeekdayWeekendSchedule class in schedules.rb

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-Beopt#70]
Currently, month-to-month hourly schedules cannot vary. We need them to in order to accommodate overlapping seasons where cooling setpoints < heating setpoints. I suggest, as inputs, 12-element arrays of the 24 comma-separated value strings.

**Comment by shorowit** [comment]
The HourlyByMonthSchedule class in schedule.rb allows this. However, note that it takes in nested arrays rather than an array of strings. Let me know if you have problems using it. You can see an example of its use by looking at the Lighting measure.

At some point I should make the two classes in schedules.rb have consistent arguments (string vs array) -- though they are inconsistent for good reason.

**Comment by joseph-robertson** [comment]
@shorowit Can that class handle weekday vs weekend?

**Comment by shorowit** [comment]
Nope. Will implement.
