### ISSUE TITLE
Translating electric quipment unit object to idf

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BEopt#78]
Need to associate a space or spacetype with each electric equipment object so that it is translated.

Need in idf for airflow measure.

**Comment by shorowit** [comment]
Is this specific to the electric equipment objects used for the unit beds/baths/spaces specification? I intentionally didn't associate them with spaces so they wouldn't be translated to idf. I don't see why the airflow measure should need this since we can still get the info from the model (runner.lastOpenStudiomodel or whatever).

**Comment by joseph-robertson** [comment]
Just saw your comment. You're right, can get it from lastOpenStudioModel.
